name: Haskell CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Haskell
      uses: haskell/actions/setup@v2
      with:
        ghc-version: '9.2.8' # Set your desired GHC version
        cabal-version: 'latest'

    - name: Cache cabal store
      uses: actions/cache@v4
      with:
        path: |
          ~/.cabal/store
        key: ${{ runner.os }}-cabal-${{ hashFiles('**/*.cabal') }}
        restore-keys: |
          ${{ runner.os }}-cabal-

    - name: Build
      run: cabal build all

    - name: Test
      run: cabal test all